import { Supplement } from '@/types';

export const supplements: Supplement[] = [
  {
    id: 'sleep-recovery',
    name: 'Sleep & Recovery',
    tagline: 'Wake up refreshed, every morning',
    ingredients: [
      'Magnesium Glycinate 400mg',
      'L-Theanine 200mg',
      'Ashwagandha KSM-66 600mg',
      'Melatonin 3mg',
    ],
    goals: ['sleep', 'stress', 'recovery', 'anxiety', 'relaxation'],
    price: '$1.98/day',
    format: 'Capsules or Powder',
  },
  {
    id: 'immune-defense',
    name: 'Immune Defense',
    tagline: 'Stay strong through every season',
    ingredients: [
      'Vitamin C 1000mg',
      'Vitamin D3 5000 IU',
      'Zinc Bisglycinate 25mg',
      'Elderberry Extract 500mg',
      'Quercetin 500mg',
    ],
    goals: ['immunity', 'energy', 'wellness', 'prevention', 'sick'],
    price: '$2.10/day',
    format: 'Capsules',
  },
  {
    id: 'beauty-glow',
    name: 'Beauty Glow',
    tagline: 'Radiance from within',
    ingredients: [
      'Biotin 10,000mcg',
      'Marine Collagen 5g',
      'Vitamin E 400 IU',
      'Hyaluronic Acid 200mg',
      'Astaxanthin 12mg',
    ],
    goals: ['beauty', 'skin', 'hair', 'nails', 'anti-aging', 'glow'],
    price: '$2.45/day',
    format: 'Powder',
  },
  {
    id: 'stress-calm',
    name: 'Stress & Calm',
    tagline: 'Find your center, keep your edge',
    ingredients: [
      'Ashwagandha KSM-66 600mg',
      'Rhodiola Rosea 400mg',
      'Magnesium Glycinate 300mg',
      'B-Complex (B6, B12, Folate)',
      'L-Theanine 200mg',
    ],
    goals: ['stress', 'focus', 'mood', 'anxiety', 'mental health', 'calm'],
    price: '$2.20/day',
    format: 'Capsules or Powder',
  },
  {
    id: 'heart-health',
    name: 'Heart & Circulation',
    tagline: 'Support your most important muscle',
    ingredients: [
      'Omega-3 Fish Oil 2g',
      'CoQ10 200mg',
      'Magnesium Taurate 400mg',
      'Vitamin K2 (MK-7) 200mcg',
      'Berberine 500mg',
    ],
    goals: ['heart', 'circulation', 'cholesterol', 'blood pressure', 'cardiovascular'],
    price: '$2.75/day',
    format: 'Capsules',
  },
  {
    id: 'weight-management',
    name: 'Metabolism & Weight',
    tagline: 'Fuel your goals, naturally',
    ingredients: [
      'Green Tea Extract (EGCG) 500mg',
      'L-Carnitine 1500mg',
      'CLA 1000mg',
      'Chromium Picolinate 200mcg',
      'Berberine 500mg',
    ],
    goals: ['weight', 'metabolism', 'energy', 'fat loss', 'body composition', 'diet'],
    price: '$2.58/day',
    format: 'Capsules or Powder',
  },
  {
    id: 'energy-focus',
    name: 'Energy & Focus',
    tagline: 'Peak performance, all day long',
    ingredients: [
      'Vitamin B12 (Methylcobalamin) 1000mcg',
      'Rhodiola Rosea 400mg',
      'Alpha-GPC 300mg',
      'Iron Bisglycinate 18mg',
      'CoQ10 100mg',
    ],
    goals: ['energy', 'focus', 'performance', 'productivity', 'mental clarity', 'fatigue'],
    price: '$2.35/day',
    format: 'Capsules',
  },
];
